# Generated by mc: 8:09 5.6.2021.
#
	.data
	.text
main:	addi	$sp, $sp, -4		# push fp
	sw	$fp, 0($sp)
	move	$fp, $sp		# fp <- sp
	addi	$sp, $sp, -76		# allocate locals
	li	$v0, 0
	sw	$v0, -72($fp)
	li	$v0, 1
	sw	$v0, -8($fp)
	li	$v0, 2
	sw	$v0, -12($fp)
	lw	$t1, -8($fp)
	lw	$t2, -12($fp)
	add	$v0, $t1, $t2
	sw	$v0, -16($fp)
	li	$v0, 3
	sw	$v0, -20($fp)
	lw	$t1, -16($fp)
	lw	$t2, -20($fp)
	add	$v0, $t1, $t2
	sw	$v0, -24($fp)
	li	$v0, 4
	sw	$v0, -28($fp)
	li	$v0, 5
	sw	$v0, -32($fp)
	lw	$t1, -28($fp)
	lw	$t2, -32($fp)
	add	$v0, $t1, $t2
	sw	$v0, -36($fp)
	li	$v0, 6
	sw	$v0, -40($fp)
	lw	$t1, -36($fp)
	lw	$t2, -40($fp)
	add	$v0, $t1, $t2
	sw	$v0, -44($fp)
	li	$v0, 7
	sw	$v0, -48($fp)
	li	$v0, 8
	sw	$v0, -52($fp)
	lw	$t1, -48($fp)
	lw	$t2, -52($fp)
	add	$v0, $t1, $t2
	sw	$v0, -56($fp)
	li	$v0, 9
	sw	$v0, -60($fp)
	lw	$t1, -56($fp)
	lw	$t2, -60($fp)
	add	$v0, $t1, $t2
	sw	$v0, -64($fp)
	lw	$t1, -24($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	lw	$t1, -44($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	lw	$t1, -64($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	addi	$sp, $sp, -4		# push 
	sw	$ra, 0($sp)
	jal	add3
	lw	$ra, 0($sp)		# pop ra
	addi	$sp, $sp, 4
	addi	$sp, $sp, 12		# deallocate args
	sw	$v0, -68($fp)
	lw	$v0, -68($fp)
	sw	$v0, -72($fp)
	lw	$v0, -72($fp)
	sw	$v0, -76($fp)
	lw	$v0, -76($fp)
	move	$sp, $fp
	lw	$fp, 0($sp)		# pop restore fp
	addi	$sp, $sp, 4
	li	$v0, 17			# $v0 gets exit code for syscall
	syscall				# Exit here
add3:	addi	$sp, $sp, -4		# push fp
	sw	$fp, 0($sp)
	move	$fp, $sp		# fp <- sp
	addi	$sp, $sp, -12		# allocate locals
	lw	$t1, 16($fp)
	lw	$t2, 12($fp)
	add	$v0, $t1, $t2
	sw	$v0, -4($fp)
	lw	$t1, -4($fp)
	lw	$t2, 8($fp)
	add	$v0, $t1, $t2
	sw	$v0, -8($fp)
	lw	$v0, -8($fp)
	sw	$v0, -12($fp)
	lw	$v0, -12($fp)
	move	$sp, $fp
	lw	$fp, 0($sp)		# pop restore fp
	addi	$sp, $sp, 4
	jr	$ra				# return
